# Generated by Django 4.2.7 on 2023-11-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('ejob', models.CharField(max_length=100)),
                ('esal', models.IntegerField()),
            ],
        ),
    ]
